version: '3'

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Add any other environment variables your app needs

  # If you're using a database, you can add it here
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: your_db_name
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: